import re

kyr = {
    'app_name': 'MEDLINE',
    'login': 'Кирүү',
    'dont_have_account': "Аккаунтуңуз жокпу?",
    'register': 'Катталуу',
    'email': 'Email',
    'password': 'Сырсөз',
    'password_min_length': 'Кеминде 6 белги',
    'forgot_password': 'Сырсөздү унуттуңузбу?',
    'reset_password_hint': 'Сырсөздү калыбына келтирүү үчүн email дарегиңизди киргизиңиз.',
    'reset_email_sent': 'Сырсөз калыбына келтирүү шилтемеси жөнөтүлдү',
    'send': 'Жөнөтүү',
    'go_to_login': 'Кирүү барагына өтүү',
    'registration_success': 'Ийгиликтүү катталдыңыз',
    'invalid_email': 'Туура эмес email',
    'select_role': 'Ролду тандаңыз',
    'admin_registration': 'Админ каттоо',
    'admin_registration_subtitle': 'Клиника администратору катары катталыңыз',
    'admin_register_info': 'Бул барак админдер үчүн гана. Дарыгерлер жана ресепшндер админдер тарабынан кошулат.',
    'register_as_admin': 'Админ катары катталуу',
    'admin_panel': 'Админ Панели',
    'doctor_panel': 'Дарыгер Панели',
    'receptionist_panel': 'Кабылдама Панели',
    'pharmacy_panel': 'Дарыкана панели',
    'laboratory_panel': 'Лаборатория панели',
    'logout': 'Чыгуу',
    'logout_confirm': 'Чын эле чыккыңыз келеби?',
    'cancel': 'Жокко чыгаруу',
    'language': 'Тил',
    'refresh': 'Жаңылоо',
    'error': 'Ката',
    'success': 'Ийгиликтүү',
    'loading': 'Жүктөлүүдө...',
    'save': 'Сактоо',
    'saving': 'Сакталууда...',
    'clear': 'Тазалоо',
    'edit': 'Өзгөртүү',
    'delete': 'Өчүрүү',
    'add': 'Кошуу',
    'fill_all_fields': 'Бардык талааларды толтуруңуз',
    'statistics': 'Статистика',
    'patients': 'Бейтаптар',
    'staff': 'Кызматкерлер',
    'add_staff': 'Кызматкер кошуу',
    'no_staff': 'Кызматкерлер табылган жок',
    'add_staff_hint': 'Жогорудагы баскыч менен жаңы кызматкер кошуңуз',
    'doctors': 'Дарыгерлер',
    'receptionists': 'Ресепшндер',
    'pharmacists': 'Фармацевттер',
    'pharmacist': 'Фармацевт',
    'laboratory_staff': 'Лаборанттар',
    'laboratory': 'Лаборатория',
    'created': 'Түзүлгөн',
    'name': 'Аты',
    'role': 'Рол',
    'doctor': 'Дарыгер',
    'receptionist': 'Ресепшн',
    'name_required': 'Атын киргизүү милдеттүү',
    'staff_added_success': 'Кызматкер ийгиликтүү кошулду',
    'edit_staff': 'Кызматкерди өзгөртүү',
    'staff_updated_success': 'Кызматкер ийгиликтүү жаңыланды',
    'delete_staff': 'Кызматкерди өчүрүү',
    'delete_staff_confirm': 'Кызматкерди өчүргүңүз келеби',
    'staff_deleted_success': 'Кызматкер ийгиликтүү өчүрүлдү',
    'patient_info': 'Бейтап маалыматы',
    'surname': 'Фамилиясы',
    'queue': 'Кезек',
    'address': 'Дарек',
    'issue': 'Арыз',
    'price': 'Баа',
    'payment_status': 'Төлөм абалы',
    'payment_completed': 'Төлөндү',
    'payment_pending': 'Төлөнгөн жок',
    'fill_required_fields': 'Бардык милдеттүү талааларды толтуруңуз',
    'field_required': 'Бул талааны толтуруу шарт',
    'select_doctor': 'Дарыгерди тандаңыз',
    'no_doctors': 'Дарыгерлер табылган жок',
    'refresh_doctors': 'Дарыгерлерди жаңылоо',
    'patient_registered': 'Бейтап ийгиликтүү катталды',
    'status': 'Абал',
    'waiting': 'Күтүүдө',
    'completed': 'Аткарылды',
    'patients_list': 'Бейтаптар тизмеси',
    'all_patients': 'Бардык бейтаптар',
    'waiting_patients': 'Күтүп жаткан бейтаптар',
    'completed_patients': 'Аяктаган бейтаптар',
    'search_patients': 'Бейтаптарды издөө...',
    'no_patients': 'Бейтаптар тизмеси бош',
    'no_waiting_patients': 'Күтүп жаткан бейтаптар жок',
    'no_results': 'Эч нерсе табылган жок',
    'total': 'Жалпы',
    'paid': 'Төлөнгөн',
    'unpaid': 'Төлөнбөгөн',
    'all': 'Баардыгы',
    'total_patients': 'Жалпы бейтаптар',
    'total_revenue': 'Жалпы киреше',
    'today': 'Бүгүн',
    'week': 'Апта',
    'month': 'Ай',
    'today_stats': 'Бүгүнкү статистика',
    'week_stats': 'Апталык статистика',
    'month_stats': 'Айлык статистика',
    'doctor_statistics': 'Дарыгерлер статистикасы',
    'recent_patients': 'Акыркы бейтаптар',
    'patients_not_found': 'Бейтаптар табылган жок',
    'no_data': 'Маалымат жок',
    'period_statistics': 'Мезгил боюнча статистика',
    'this_week': 'Бул апта',
    'this_month': 'Бул ай',
    'diagnosis': 'Диагноз',
    'add_diagnosis': 'Диагноз коюу',
    'enter_diagnosis': 'Диагнозду киргизиңиз',
    'diagnosis_saved': 'Диагноз сакталды',
    'tests': 'Анализдер',
    'results': 'Жыйынтыктар',
    'search_patient': 'Бейтап атын издеңиз...',
    'add_test': 'Жаңы анализ кошуу',
    'no_tests': 'Азырынча анализ жок',
    'add_test_hint': 'Жогорудагы баскыч менен жаңы анализ кошуңуз',
    'patient_name': 'Бейтап А.Ж.А.',
    'phone': 'Телефон номери',
    'test_type': 'Анализ түрү',
    'blood_test': 'Кан анализи',
    'urine_test': 'Заара анализи',
    'xray': 'Рентген',
    'ultrasound': 'УЗИ',
    'ecg': 'ЭКГ',
    'mri': 'МРТ',
    'notes': 'Кошумча эскертмелер',
    'invalid_price': 'Баа туура эмес киргизилди',
    'test_added': 'Жаңы анализ ийгиликтүү кошулду',
    'pending': 'Күтүүдө',
    'result': 'Жыйынтык',
    'add_result': 'Жыйынтык кошуу',
    'mark_paid': 'Төлөнгөн деп белгилөө',
    'delete_test': 'Анализди өчүрүү',
    'delete_test_confirm': 'Бул анализди өчүргүңүз келеби? Бул аракетти кайтаруу мүмкүн эмес!',
    'payment_updated': 'Төлөм абалы жаңыланды',
    'test_deleted': 'Анализ өчүрүлдү',
    'enter_result': 'Жыйынтыкты киргизиңиз',
    'result_saved': 'Жыйынтык сакталды',
    'lab_statistics': 'Лаборатория статистикасы',
    'test_status': 'Анализ абалы',
    'medicines': 'Дарылар',
    'sales': 'Сатуулар',
    'search_medicine': 'Дары издөө...',
    'add_medicine': 'Дары кошуу',
    'medicine_name': 'Дары аты',
    'category': 'Категория',
    'tablets': 'Таблетка',
    'syrup': 'Сироп',
    'injection': 'Укол',
    'ointment': 'Мазь',
    'drops': 'Тамчы',
    'quantity': 'Саны',
    'expiry_date': 'Жарактуулук мөөнөтү',
    'select_date': 'Күндү тандаңыз',
    'description': 'Сүрөттөмө',
    'no_medicines': 'Дарылар табылган жок',
    'add_medicine_hint': 'Жаңы дары кошуу үчүн баскычты басыңыз',
    'medicine_added': 'Дары ийгиликтүү кошулду',
    'medicine_updated': 'Дары ийгиликтүү жаңыланды',
    'medicine_deleted': 'Дары өчүрүлдү',
    'edit_medicine': 'Дарыны өзгөртүү',
    'delete_medicine': 'Дарыны өчүрүү',
    'delete_medicine_confirm': 'Бул дарыны өчүргүңүз келеби?',
    'sell': 'Сатуу',
    'sell_medicine': 'Дары сатуу',
    'available': 'Бар',
    'invalid_quantity': 'Саны туура эмес киргизилди',
    'not_enough_stock': 'Кампада жетиштүү дары жок',
    'sale_completed': 'Сатуу ийгиликтүү аякталды',
    'no_sales': 'Сатуулар табылган жок',
    'pcs': 'даана',
    'low_stock': 'Аз калды',
    'expiring_soon': 'Мөөнөтү бүтөт',
    'sales_statistics': 'Сатуу статистикасы',
    'inventory_alerts': 'Кампа эскертүүлөрү',
    'hospitalization': 'Стационар',
    'admit_patient': 'Бейтапты жаткыруу',
    'hospitalized': 'Жаткырылгандар',
    'rooms': 'Бөлмөлөр',
    'room': 'Бөлмө',
    'select_room': 'Бөлмөнү тандаңыз',
    'no_available_rooms': 'Бош бөлмөлөр жок',
    'admission_reason': 'Жаткыруу себеби',
    'initial_diagnosis': 'Алгачкы диагноз',
    'admit': 'Жаткыруу',
    'patient_admitted_successfully': 'Бейтап ийгиликтүү жаткырылды',
    'no_hospitalized_patients': 'Жаткырылган бейтаптар жок',
    'discharge': 'Чыгаруу',
    'discharge_notes': 'Чыгаруу эскертмелери',
    'patient_discharged_successfully': 'Бейтап ийгиликтүү чыгарылды',
    'rooms_management': 'Бөлмөлөрдү башкаруу',
    'add_room': 'Бөлмө кошуу',
    'room_number': 'Бөлмө номери',
    'room_type': 'Бөлмө түрү',
    'number_of_beds': 'Керебеттер саны',
    'beds': 'Керебеттер',
    'room_added_successfully': 'Бөлмө ийгиликтүү кошулду',
    'occupied': 'Бош эмес',
    'current_patient': 'Учурдагы бейтап',
    'no_rooms': 'Бөлмөлөр табылган жок',
    'close': 'Жабуу',
    'confirm_deletion': 'Өчүрүүнү ырастоо',
    'delete_room_confirmation': 'Бул бөлмөнү өчүргүңүз келеби?',
    'room_deleted_successfully': 'Бөлмө ийгиликтүү өчүрүлдү',
    'cannot_delete_occupied_room': 'Бош эмес бөлмөнү өчүрүүгө болбойт',
    'room_occupied': 'Бош эмес',
    'current_patients': 'Учурдагы бейтаптар',
    'history': 'Тарых',
    'coming_soon': 'Жакында...',
    'copyright_text': '© 2026 MEDLINE. Бардык укуктар корголгон.',
    'clinic_management_system': 'Клиника башкаруу системасы',
}

with open(r'd:\medline\lib\providers\language_provider.dart', 'r', encoding='utf-8') as f:
    content = f.read()

lines = content.split('\n')
new_lines = []
current_key = None

for line in lines:
    new_lines.append(line)
    
    # Track current translation key
    key_match = re.match(r"\s+'(\w+)':\s*\{", line)
    if key_match:
        current_key = key_match.group(1)
    
    # After RUS line, add KYR if we have a translation
    if current_key and re.match(r"\s+'RUS':\s*'", line) and current_key in kyr:
        indent = re.match(r"(\s+)", line).group(1)
        kyr_val = kyr[current_key]
        new_lines.append(f"{indent}'KYR': '{kyr_val}',")

# Update changeLanguage to accept KYR
result = '\n'.join(new_lines)
result = result.replace(
    "if (['UZB', 'ENG', 'RUS'].contains(languageCode))",
    "if (['UZB', 'ENG', 'RUS', 'KYR'].contains(languageCode))"
)

with open(r'd:\medline\lib\providers\language_provider.dart', 'w', encoding='utf-8') as f:
    f.write(result)

print('Done! KYR translations added successfully.')
